# makefile for the game of war (h1.cpp)
h1: h1.cpp card.cpp deck.cpp card.o deck.o
	g++ h1.cpp card.o deck.o -o h1
deck: deck.cpp
	g++ -c deck.cpp -o deck.o
card: card.cpp
	g++ -c card.cpp -o card.o
